# Generated by Django 5.2.1 on 2025-06-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="km",
            field=models.IntegerField(default=0),
        ),
    ]
