# Generated by Django 5.2.1 on 2025-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_car_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="km",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
